//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public Ad()
        {
            this.AdImages = new HashSet<AdImage>();
            this.AdsLikes = new HashSet<AdsLike>();
            this.AdsLocations = new HashSet<AdsLocation>();
            this.AdViews = new HashSet<AdView>();
            this.Bids = new HashSet<Bid>();
            this.Comments = new HashSet<Comment>();
            this.Reporteds = new HashSet<Reported>();
            this.MobileAds = new HashSet<MobileAd>();
            this.LaptopAds = new HashSet<LaptopAd>();
            this.CarAds = new HashSet<CarAd>();
        }
    
        public int Id { get; set; }
        public string category { get; set; }
        public string postedBy { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> price { get; set; }
        public string isnegotiable { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<AdImage> AdImages { get; set; }
        public virtual ICollection<AdsLike> AdsLikes { get; set; }
        public virtual ICollection<AdsLocation> AdsLocations { get; set; }
        public virtual ICollection<AdView> AdViews { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Reported> Reporteds { get; set; }
        public virtual ICollection<MobileAd> MobileAds { get; set; }
        public virtual ICollection<LaptopAd> LaptopAds { get; set; }
        public virtual ICollection<CarAd> CarAds { get; set; }
    }
}
