//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaptopModel
    {
        public LaptopModel()
        {
            this.LaptopAds = new HashSet<LaptopAd>();
        }
    
        public int Id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
    
        public virtual LaptopBrand LaptopBrand { get; set; }
        public virtual ICollection<LaptopAd> LaptopAds { get; set; }
    }
}
