//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5_SeedProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class popularPlace
    {
        public popularPlace()
        {
            this.AdsLocations = new HashSet<AdsLocation>();
        }
    
        public int Id { get; set; }
        public string cityId { get; set; }
        public string name { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<AdsLocation> AdsLocations { get; set; }
    }
}
